name: Upload Media to Cloudinary
on:
  push:
    paths:
      - 'content/images/**'
      - 'content/posts/**'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to Cloudinary
        uses: cloudinary/actions@master
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        with:
          folder: 'myblog'
          source: './content/images/*'
          overwrite: true
